### ISSUE TITLE
CustomEvent  constructor

### ISSUE THREAD

**Issue by nuxodin** [jonathantneal/EventListener#3]
The constructor "CustomEvent"
Takes as the second argument a object like:
{
  bubbles:true,
  cancelable:true,
  detail:{x:1,y:2}
}

https://dvcs.w3.org/hg/domcore/raw-file/tip/Overview.html#concept-event

**Comment by mxdubois** [comment]
MDN indicates the `CustomEvent` constructor also takes a dictionary object as the second parameter: https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent

**Comment by mxdubois** [comment]
Oh, it looks like the `CustomEvent` polyfill in this repo conforms with the spec. The README just needs to be updated.
